-- =============================================================================
-- 1. VALIDATION CONSTRAINTS (CHECK & UNIQUE)
-- =============================================================================

-- USER
ALTER TABLE T_SINL_USER ADD CONSTRAINT UK_T_SINL_USER_EMAIL UNIQUE (txt_email);
ALTER TABLE T_SINL_USER ADD CONSTRAINT CK_T_SINL_USER_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_USER ADD CONSTRAINT CK_T_SINL_USER_IND_DELETED CHECK (ind_deleted IN ('Y','N'));
ALTER TABLE T_SINL_USER ADD CONSTRAINT CK_T_SINL_USER_EMAIL_VERIFIED CHECK (ind_email_verified IN ('Y','N'));
ALTER TABLE T_SINL_USER ADD CONSTRAINT CK_USER_STATUS CHECK (sta_user IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'BLOCKED'));

-- CATEGORY
ALTER TABLE T_SINL_CATEGORY ADD CONSTRAINT CK_T_SINL_CATEGORY_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_CATEGORY ADD CONSTRAINT CK_T_SINL_CATEGORY_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- COURSE
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT UK_T_SINL_COURSE_SLUG UNIQUE (txt_slug);
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT CK_T_SINL_COURSE_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT CK_T_SINL_COURSE_IND_DELETED CHECK (ind_deleted IN ('Y','N'));
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT CK_T_SINL_COURSE_IND_PAID CHECK (ind_paid IN ('Y','N'));
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT CK_COURSE_STATUS CHECK (sta_course IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'));

-- MODULE
ALTER TABLE T_SINL_MODULE ADD CONSTRAINT CK_T_SINL_MODULE_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_MODULE ADD CONSTRAINT CK_T_SINL_MODULE_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- LESSON
ALTER TABLE T_SINL_LESSON ADD CONSTRAINT CK_T_SINL_LESSON_IND_REQ_COMP CHECK (ind_require_completion IN ('Y','N'));
ALTER TABLE T_SINL_LESSON ADD CONSTRAINT CK_T_SINL_LESSON_IND_VISIBLE CHECK (ind_visible IN ('Y','N'));
ALTER TABLE T_SINL_LESSON ADD CONSTRAINT CK_T_SINL_LESSON_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_LESSON ADD CONSTRAINT CK_T_SINL_LESSON_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- LESSON CONTENT
ALTER TABLE T_SINL_LESSON_CONTENT ADD CONSTRAINT CK_T_SINL_LESSON_CONTENT_IND_HAS_QUIZ CHECK (ind_has_quiz IN ('Y','N'));
ALTER TABLE T_SINL_LESSON_CONTENT ADD CONSTRAINT CK_T_SINL_LESSON_CONTENT_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_LESSON_CONTENT ADD CONSTRAINT CK_T_SINL_LESSON_CONTENT_IND_DELETED CHECK (ind_deleted IN ('Y','N'));
ALTER TABLE T_SINL_LESSON_CONTENT ADD CONSTRAINT CK_T_SINL_LESSON_CONTENT_IND_MAIN CHECK (ind_main_content IN ('Y','N'));

-- QUIZ
ALTER TABLE T_SINL_QUIZ ADD CONSTRAINT CK_T_SINL_QUIZ_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_QUIZ ADD CONSTRAINT CK_T_SINL_QUIZ_IND_DELETED CHECK (ind_deleted IN ('Y','N'));
ALTER TABLE T_SINL_QUIZ ADD CONSTRAINT CK_T_SINL_QUIZ_IND_RANDOM CHECK (ind_random_order IN ('Y','N'));

-- QUIZ QUESTION
ALTER TABLE T_SINL_QUIZ_QUESTION ADD CONSTRAINT CK_T_SINL_QUIZ_QUESTION_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_QUIZ_QUESTION ADD CONSTRAINT CK_T_SINL_QUIZ_QUESTION_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- QUIZ ANSWER OPTION
ALTER TABLE T_SINL_QUIZ_ANSWER_OPTION ADD CONSTRAINT CK_T_SINL_Q_ANS_OPT_IND_CORR CHECK (ind_correct IN ('Y','N'));
ALTER TABLE T_SINL_QUIZ_ANSWER_OPTION ADD CONSTRAINT CK_T_SINL_Q_ANS_OPT_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_QUIZ_ANSWER_OPTION ADD CONSTRAINT CK_T_SINL_Q_ANS_OPT_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- USER QUIZ ANSWER
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT CK_T_SINL_USER_Q_ANS_IND_CORR CHECK (ind_correct IN ('Y','N'));
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT CK_T_SINL_USER_Q_ANS_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT CK_T_SINL_USER_Q_ANS_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- USER QUIZ ATTEMPT
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT CK_T_SINL_UQA_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT CK_T_SINL_UQA_IND_DELETED CHECK (ind_deleted IN ('Y','N'));
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT CK_T_SINL_UQA_IND_PASSED CHECK (ind_passed IN ('Y','N'));
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT CK_T_SINL_UQA_STATUS CHECK (sta_attempt IN ('STARTED','FINISHED','CANCELLED'));

-- USER COURSE
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT CK_T_SINL_USER_COURSE_STA CHECK (sta_enrollment IN ('ENROLLED','IN_PROGRESS','COMPLETED','CANCELLED','REFUNDED','EXPIRED'));
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT CK_T_SINL_USER_COURSE_IND_CERT CHECK (ind_certificate_issued IN ('Y','N'));
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT CK_T_SINL_USER_COURSE_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT CK_T_SINL_USER_COURSE_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- USER LESSON PROGRESS
ALTER TABLE T_SINL_USER_LESSON_PROGRESS ADD CONSTRAINT CK_T_SINL_USER_LESSON_PROGRESS_IND_COMPLETED CHECK (ind_completed IN ('Y','N'));
ALTER TABLE T_SINL_USER_LESSON_PROGRESS ADD CONSTRAINT CK_T_SINL_USER_LESSON_PROGRESS_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_USER_LESSON_PROGRESS ADD CONSTRAINT CK_T_SINL_USER_LESSON_PROGRESS_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- REVIEW
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT CK_REVIEW_STATUS CHECK (sta_review IN ('PENDING', 'APPROVED', 'REJECTED'));
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT CK_T_SINL_REVIEW_IND_ANON CHECK (ind_anonymous IN ('Y','N'));
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT CK_T_SINL_REVIEW_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT CK_T_SINL_REVIEW_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- REFRESH TOKENS
ALTER TABLE T_SINL_REFRESH_TOKENS ADD CONSTRAINT CK_T_SINL_REF_TOKEN_IND_ACTIVE CHECK (ind_active IN ('Y','N'));
ALTER TABLE T_SINL_REFRESH_TOKENS ADD CONSTRAINT CK_T_SINL_REF_TOKEN_IND_DELETED CHECK (ind_deleted IN ('Y','N'));

-- =============================================================================
-- 2. FOREIGN KEYS (RELATIONSHIPS)
-- =============================================================================
ALTER TABLE T_SINL_CATEGORY ADD CONSTRAINT FK_CAT_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_CATEGORY ADD CONSTRAINT FK_CAT_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT FK_COURSE_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT FK_COURSE_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_MODULE ADD CONSTRAINT FK_MODULE_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_MODULE ADD CONSTRAINT FK_MODULE_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_LESSON ADD CONSTRAINT FK_LESSON_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_LESSON ADD CONSTRAINT FK_LESSON_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_LESSON_CONTENT ADD CONSTRAINT FK_LESSON_CONTENT_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_LESSON_CONTENT ADD CONSTRAINT FK_LESSON_CONTENT_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_QUIZ ADD CONSTRAINT FK_QUIZ_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_QUIZ ADD CONSTRAINT FK_QUIZ_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_QUIZ_QUESTION ADD CONSTRAINT FK_QQUESTION_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_QUIZ_QUESTION ADD CONSTRAINT FK_QQUESTION_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_QUIZ_ANSWER_OPTION ADD CONSTRAINT FK_QANSOPT_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_QUIZ_ANSWER_OPTION ADD CONSTRAINT FK_QANSOPT_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT FK_UQANS_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT FK_UQANS_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT FK_UQA_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT FK_UQA_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT FK_UCOURSE_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT FK_UCOURSE_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_LESSON_PROGRESS ADD CONSTRAINT FK_ULP_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_LESSON_PROGRESS ADD CONSTRAINT FK_ULP_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT FK_REVIEW_CREATED_BY FOREIGN KEY (cod_created_by) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT FK_REVIEW_UPDATED_BY FOREIGN KEY (cod_updated_by) REFERENCES T_SINL_USER(cod_user);


ALTER TABLE T_SINL_CATEGORY ADD CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (cod_parent_category) REFERENCES T_SINL_CATEGORY(cod_category);
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT FK_COURSE_INSTRUCTOR FOREIGN KEY (cod_user) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_COURSE ADD CONSTRAINT FK_COURSE_CATEGORY FOREIGN KEY (cod_category) REFERENCES T_SINL_CATEGORY(cod_category);
ALTER TABLE T_SINL_MODULE ADD CONSTRAINT FK_MODULE_COURSE FOREIGN KEY (cod_course) REFERENCES T_SINL_COURSE(cod_course) ON DELETE CASCADE;
ALTER TABLE T_SINL_LESSON ADD CONSTRAINT FK_LESSON_MODULE FOREIGN KEY (cod_module) REFERENCES T_SINL_MODULE(cod_module) ON DELETE CASCADE;
ALTER TABLE T_SINL_LESSON_CONTENT ADD CONSTRAINT FK_LESSONCONTENT_LESSON FOREIGN KEY (cod_lesson) REFERENCES T_SINL_LESSON(cod_lesson) ON DELETE CASCADE;
ALTER TABLE T_SINL_QUIZ ADD CONSTRAINT FK_QUIZ_MODULE FOREIGN KEY (cod_module) REFERENCES T_SINL_MODULE(cod_module);
ALTER TABLE T_SINL_QUIZ_QUESTION ADD CONSTRAINT FK_QQUESTION_QUIZ FOREIGN KEY (cod_quiz) REFERENCES T_SINL_QUIZ(cod_quiz) ON DELETE CASCADE;
ALTER TABLE T_SINL_QUIZ_ANSWER_OPTION ADD CONSTRAINT FK_QANSOPT_QUESTION FOREIGN KEY (cod_quiz_question) REFERENCES T_SINL_QUIZ_QUESTION(cod_quiz_question) ON DELETE CASCADE;
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT FK_UQANS_USER FOREIGN KEY (cod_user) REFERENCES T_SINL_USER(cod_user) ON DELETE CASCADE;
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT FK_UQANS_QUESTION FOREIGN KEY (cod_quiz_question) REFERENCES T_SINL_QUIZ_QUESTION(cod_quiz_question) ON DELETE CASCADE;
ALTER TABLE T_SINL_USER_QUIZ_ANSWER ADD CONSTRAINT FK_UQANS_OPTION FOREIGN KEY (cod_quiz_answer_option) REFERENCES T_SINL_QUIZ_ANSWER_OPTION(cod_quiz_answer_option);
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT FK_UQA_USER FOREIGN KEY (cod_user) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_USER_QUIZ_ATTEMPT ADD CONSTRAINT FK_UQA_QUIZ FOREIGN KEY (cod_quiz) REFERENCES T_SINL_QUIZ(cod_quiz);
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT FK_UCOURSE_USER FOREIGN KEY (cod_user) REFERENCES T_SINL_USER(cod_user) ON DELETE CASCADE;
ALTER TABLE T_SINL_USER_COURSE ADD CONSTRAINT FK_UCOURSE_COURSE FOREIGN KEY (cod_course) REFERENCES T_SINL_COURSE(cod_course) ON DELETE CASCADE;
ALTER TABLE T_SINL_USER_LESSON_PROGRESS ADD CONSTRAINT FK_ULP_USER FOREIGN KEY (cod_user) REFERENCES T_SINL_USER(cod_user) ON DELETE CASCADE;
ALTER TABLE T_SINL_USER_LESSON_PROGRESS ADD CONSTRAINT FK_ULP_LESSON FOREIGN KEY (cod_lesson) REFERENCES T_SINL_LESSON(cod_lesson) ON DELETE CASCADE;
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT FK_REVIEW_USER FOREIGN KEY (cod_user) REFERENCES T_SINL_USER(cod_user);
ALTER TABLE T_SINL_REVIEW ADD CONSTRAINT FK_REVIEW_COURSE FOREIGN KEY (cod_course) REFERENCES T_SINL_COURSE(cod_course) ON DELETE CASCADE;
ALTER TABLE T_SINL_REFRESH_TOKENS ADD CONSTRAINT FK_SINL_REFRESH_TOK_USER FOREIGN KEY (cod_user) REFERENCES T_SINL_USER(cod_user);